spring.application.name=product-service
server.port=8082


# ========================================
# MongoDB Atlas
# ========================================

spring.mongodb.uri=${PRODUCT_MONGO_URI}
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}

jwt.expiration-ms=${JWT_EXPIRATION_MS}

# ========================================
# Eureka
# ========================================

eureka.client.service-url.defaultZone=${eureka.client.service-url.defaultZone}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

spring.data.redis.host=${spring.data.redis.host}
spring.data.redis.port=${spring.data.redis.port}

spring.cache.type=redis

# ========================================
# Actuator
# ========================================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

management.health.mongodb.enabled=false